# Generated by Django 4.2.5 on 2023-10-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articl',
            field=models.IntegerField(blank=True, null=True, verbose_name='артикул'),
        ),
    ]
