# Generated by Django 4.2.5 on 2023-10-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_articl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='product',
            name='shtrih_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='product',
            name='strana',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна производитель'),
        ),
    ]
