# Generated by Django 3.2.7 on 2021-10-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notebookproduct',
            new_name='Notebook',
        ),
        migrations.RenameModel(
            old_name='SmartphoneProduct',
            new_name='Smartphone',
        ),
    ]
