# Generated by Django 3.2.7 on 2021-11-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_smartphone_sd_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='recolutions',
            new_name='resolutions',
        ),
    ]
