# Generated by Django 3.2.7 on 2021-12-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211215_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonymous_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
