# Generated by Django 3.2.7 on 2022-02-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_lighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonStationaryWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('brand', models.CharField(max_length=255, verbose_name='Брэнд')),
                ('seria', models.CharField(max_length=255, verbose_name='Серия')),
                ('articals', models.CharField(max_length=255, verbose_name='Артикул производителя')),
                ('garant_time', models.CharField(max_length=255, verbose_name='Срок гарантии')),
                ('created_cantry', models.CharField(max_length=255, verbose_name='Страна производитель')),
                ('material', models.CharField(max_length=255, verbose_name='Материал жил проводника')),
                ('conductor_class', models.CharField(max_length=255, verbose_name='Класс токопроводящей жилы')),
                ('form_wire', models.CharField(max_length=255, verbose_name='Форма жил проводника')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
