# Generated by Django 3.2.12 on 2022-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20220204_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='nonstationarywire',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
