# Generated by Django 3.2.7 on 2022-02-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20220208_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcat',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcat',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
