# Generated by Django 3.2.7 on 2022-02-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20220216_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='lighting',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='lighting',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainapp.category'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
