# Generated by Django 3.2.7 on 2022-02-17 14:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20220217_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lighting',
            old_name='count_view',
            new_name='count_views',
        ),
        migrations.RenameField(
            model_name='nonstationarywire',
            old_name='count_view',
            new_name='count_views',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='count_view',
            new_name='count_views',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='count_view',
            new_name='count_views',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='price',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='title',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainapp.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('count_view', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='lighting',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product'),
            preserve_default=False,
        ),
    ]
