# Generated by Django 3.2.7 on 2022-03-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_category_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampa',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('seria', models.CharField(max_length=255, verbose_name='Серия')),
                ('brand', models.CharField(max_length=255, verbose_name='Брэнд')),
                ('articals', models.CharField(max_length=255, verbose_name='Артикул производителя')),
                ('garant_time', models.CharField(max_length=255, verbose_name='Срок гарантии')),
                ('created_cantry', models.CharField(max_length=255, verbose_name='Страна производитель')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('plinth', models.CharField(max_length=255, verbose_name='Цоколь')),
                ('form_light', models.CharField(max_length=255, verbose_name='Форма Лампы')),
            ],
            bases=('mainapp.product',),
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='count_views',
        ),
        migrations.AddField(
            model_name='nonstationarywire',
            name='nominal_section',
            field=models.CharField(default=0, max_length=255, verbose_name='Наминально сечение проводника'),
            preserve_default=False,
        ),
    ]
