# Generated by Django 4.0.4 on 2022-08-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Lighting',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
