# Generated by Django 4.0.4 on 2022-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_remove_notebook_product_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lampa',
            options={'verbose_name': 'Объект Лампы', 'verbose_name_plural': 'Лампы'},
        ),
        migrations.AddField(
            model_name='lampa',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='color_temer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цветовая температура'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='count_prod',
            field=models.CharField(blank=True, max_length=255, verbose_name='Упаковка производителя'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='diametr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Диаметр'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='light_stream',
            field=models.CharField(blank=True, max_length=255, verbose_name='Световой поток'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='naminal_napr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Нвминальное напряжение'),
        ),
        migrations.AddField(
            model_name='lampa',
            name='potreb_power',
            field=models.CharField(blank=True, max_length=255, verbose_name='Потребляемая мощность'),
        ),
    ]
