# Generated by Django 4.0.4 on 2022-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_alter_lampa_options_lampa_color_lampa_color_temer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstationarywire',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Lampa',
        ),
        migrations.DeleteModel(
            name='NonStationaryWire',
        ),
    ]
