# Generated by Django 4.0.4 on 2022-12-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_remove_nonstationarywire_product_ptr_delete_lampa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товары в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупателя', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
