# Generated by Django 4.0.4 on 2022-12-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_alter_cart_options_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_1',
        ),
    ]
