# Generated by Django 4.0.4 on 2022-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_delete_category_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristiks',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
    ]
