# Generated by Django 4.0.4 on 2022-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_product_characteristiks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property1',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№1'),
        ),
        migrations.AddField(
            model_name='product',
            name='property10',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№10'),
        ),
        migrations.AddField(
            model_name='product',
            name='property2',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№2'),
        ),
        migrations.AddField(
            model_name='product',
            name='property3',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№3'),
        ),
        migrations.AddField(
            model_name='product',
            name='property4',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№4'),
        ),
        migrations.AddField(
            model_name='product',
            name='property5',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№5'),
        ),
        migrations.AddField(
            model_name='product',
            name='property6',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№6'),
        ),
        migrations.AddField(
            model_name='product',
            name='property7',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№7'),
        ),
        migrations.AddField(
            model_name='product',
            name='property8',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№8'),
        ),
        migrations.AddField(
            model_name='product',
            name='property9',
            field=models.CharField(blank=True, max_length=255, verbose_name='свойство_№9'),
        ),
    ]
