# Generated by Django 4.0.4 on 2023-01-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_product_date_created_product_identifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='object_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
    ]
