# Generated by Django 4.2.5 on 2023-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_news_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabillity',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristiks',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
